### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by rob420jones** [DsLNeXuS/Rashr#11]
Any chance this works on the Sony z1s

**Comment by MSF-Jarvis** [comment]
It won't work on Sony

**Comment by MSF-Jarvis** [comment]
Sony Xperia devices do not have a separate recovery partition.With the amount of work that was required by devs, you should feel lucky to have custom recoveries at all.

**Comment by rob420jones** [comment]
Agreed can say that about being lucky they have a recovery fixed the
problem got nexus lmao

**Comment by DsLNeXuS** [comment]
Hello,

it should be work on the Xperia Z devices, but only install XZDual

**Comment by rob420jones** [comment]
I had the z1s

**Comment by chetanrd** [comment]
My nexus 5 is currently rooted and on Android lollipop. Can I flash stock 6.0.1 directly?

**Comment by MSF-Jarvis** [comment]
Didn't understand what you're trying.

**Comment by chetanrd** [comment]
I am currently on 5.1.1 with TWRP recovery and rooted device. I wish to upgrade to Android 6.0.1.
1. Can I directly flash factory image downloaded from Google website using 'Recovery from Storage' option in rashr menu?
2.If yes, can I do it without losing data?

**Comment by MSF-Jarvis** [comment]
You'll most probably lose the data, but factory images are the way to go.
You should try backuping the data, flashing images and then restoring it

**Comment by chetanrd** [comment]
Thanks for your help.

Will I also lock my bootloader(lose TWRP) in the process? Same for root- will I still stay rooted?

**Comment by MSF-Jarvis** [comment]
Your bootloader stays locked, but you'll lose root. Use @Chainfire's
systemless root v2.66 and it should be fine. Just don't flash the factory
image recovery, or you'll lose TWRP

**Comment by chetanrd** [comment]
Thanks a ton!

**Comment by MSF-Jarvis** [comment]
Umm. Thanks, but I accidentally wrote locked instead of unlocked. I guess
you figured that much out

**Comment by chetanrd** [comment]
Yeah. Figured that. Just one more query. Have downloaded the android 6.0.1 image file from Google developers page. Which option do I use to flash the image
1. Recovery from storage, or
2. Kernel from storage

**Comment by MSF-Jarvis** [comment]
These can't be flashed with Rashr. You'll have to use fastboot to flash
them. Ask in your device forum at XDA for help.

**Comment by DsLNeXuS** [comment]
@chetanrd Of course you can flash a 6.0 recovery image on your device. But what is your intention? :)
Flash the every image from the update-zip excluding USERDATA and the fastboot -w command.
With rashr you are only able to flash Kernel and Recoveries
###############################
To get back to topic.
@rob420jones 
XZDual is not available for your device. And the most Sony devices doesn't have a recovery partition to flash. I'm sorry you can't use Rashr.

DsLNeXuS
