### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by breversa** [DsLNeXuS/Rashr#18]
Hi,

FYI, I proposed to include Rashr into F-Droid : https://f-droid.org/forums/topic/rashr-the-mobile-android-flash-tool/ :-)

**Comment by DsLNeXuS** [comment]
Thanks :)

**Comment by breversa** [comment]
Inclusion request migrated here : https://gitlab.com/fdroid/rfp/issues/29

**Comment by breversa** [comment]
FYI, the inclusion in F-Droid has been held because of the Google Ads dependency.

**Comment by dimqua** [comment]
@DsLNeXuS can you please provide a F-Droid build flavor?
