### ISSUE TITLE
Dialog choices not visible

### ISSUE THREAD

**Issue by JonnyTech** [DsLNeXuS/Rashr#31]
When selecting an image file, a dialog box shows with a question asking to flash. But the yes / no choice buttons do not show. They are there because they are clickable but no text is shown. Maybe the texy is white like the background. The same for the next dialog asking to reboot.

**Comment by DsLNeXuS** [comment]
Hello JonnyTech,

this problem will be fixed with the next update of Rashr.
Thanks for your report.
