### ISSUE TITLE
Wrong version code in latest release

### ISSUE THREAD

**Issue by IzzySoft** [DsLNeXuS/Rashr#32]
unfortunately, the `.apk` of the latest release (2.4.2) has the wrong version name and code:

    package: name='de.mkrtchyan.recoverytools' versionCode='113' versionName='2.4.1' platformBuildVersionName='7.1.1'

Mind retagging? Folks are wondering why they never get the 2.4.2 you "promise" by the tag :wink:

**Comment by DsLNeXuS** [comment]
Ohh thanks four your message. I will fix it with ne next release.
